name: bet_env_test
channels:
  - anaconda
  - defaults
dependencies:  
  - beautifulsoup4=4.9.3
  - openssl=1.1.1l
  - pip=21.2.4
  - python=3.9.7
  - setuptools=58.0.4
  - soupsieve=2.0.1
  - sqlite=3.36.0
  - pandas==1.3.4
  - requests==2.26.0




